"""Add about author

Revision ID: 14af4cfacae0
Revises: 16c1610da6fa
Create Date: 2023-06-17 19:04:53.783049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14af4cfacae0'
down_revision = '16c1610da6fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
